spring:
  datasource:
    url: 'jdbc:h2:mem:testdb'
    driverClassName: 'org.h2.Driver'
    username: 'sa'
    password: 'password'

  jpa:
    database-plataform: 'org.hibernate.dialect.H2Dialect'

  h2:
    console:
      enabled: true
      path: '/h2-console'

security:
  jwt:
    expiracao: 30
    chave-assinatura: ZnJhc2Ugc2VndXJhIHBhcmEgcHJvdGVnZXIgbyBzaXN0ZW1h