spring:
  datasource:
    url: 'jdbc:mysql://127.0.0.1:3306/teste?useTimezone=true&serverTimezone=UTC'
    driverClassName: 'com.mysql.cj.jdbc.Driver'
    username: 'root'
    password: 'root'

  jpa:
    database-platform: 'org.hibernate.dialect.MySQLDialect'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
security:
  jwt:
    expiracao: 30
    chave-assinatura: ZnJhc2Ugc2VndXJhIHBhcmEgcHJvdGVnZXIgbyBzaXN0ZW1h

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: '/swagger-ui.html'
  packagesToScan: 'br.dev.brunoxkk0.vendas.rest.controller'